[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[font]
size = 12
normal = { family = "MartianMono Nerd Font Mono", style = "Regular"}
italic = { family = "MartianMono Nerd Font Mono", style = "Italic"}
bold = { family = "MartianMono Nerd Font Mono", style = "Bold"}

[window]
opacity = 0.8

[keyboard]

bindings = [ { key = "F11", mods = "None", action = "ToggleFullscreen" }, ]
